(define (problem renovation-prob-2rooms-4walls-prefs)
	(:domain renovation-v1-expert-fixed)
	(:objects 
		rm1 rm2 - room
		w1 w2 w3 w4 - wall
		p1 - paint
		rlr1 - roller
		br1 - brush
		tr1 - tray
	)
	(:init
		(wall-in-room w1 rm1)
		(wall-in-room w2 rm1)
		(wall-in-room w3 rm2)
		(wall-in-room w4 rm2)
		(next-wall w1 w2)
		(next-wall w2 w3)
		(next-wall w3 w4)
		(final-wall w4)
		(current-wall w1)
		(wall-stage-prep w1)
		(wall-stage-prep w2)
		(wall-stage-prep w3)
		(wall-stage-prep w4)
		(edges-taped w1)
		(edges-taped w2)
		(edges-taped w3)
		(edges-taped w4)
		(furniture-moved rm1)
		(furniture-moved rm2)
		(floor-undamaged rm1)
		(floor-undamaged rm2)
		(tool-clean rlr1)
		(tool-clean br1)
		(tool-clean tr1)
		(= (paint-remaining p1) 12)
		(= (total-covers) 2)
		(= (total-cost) 0)
		(= (budget) 3)
	)
	(:goal (and 
		(preference furniture-moved-pref (and (furniture-moved rm1) (furniture-moved rm2)))
		(preference room-ready-pref (and (room-ready rm1) (room-ready rm2)))
		(preference first-coats (and (first-coat w1) (first-coat w2) (first-coat w3) (first-coat w4)))
		(preference second-coats (and (second-coat w1) (second-coat w2) (second-coat w3) (second-coat w4)))
		(preference edges-clean-pref (and (edges-clean w1) (edges-clean w2) (edges-clean w3) (edges-clean w4)))
		(preference tools-clean-pref (and (tool-clean rlr1) (tool-clean br1) (tool-clean tr1)))
		(preference floor-undamaged-pref (and (floor-undamaged rm1) (floor-undamaged rm2)))
		))
	(:metric minimize (+
		(total-cost)
		(is-violated furniture-moved-pref)
		(is-violated room-ready-pref)
		(is-violated first-coats)
		(is-violated second-coats)
		(is-violated edges-clean-pref)
		(is-violated tools-clean-pref)
		(is-violated floor-undamaged-pref)
		))
)
